app:
    resource: AppBundle\Controller\DefaultController
    type:     annotation

login_check:
    path:     api/login_check
    methods:  POST
    defaults: { _controller: FOSUserBundle:Security:check }

api:
    type:     rest
    resource: AppBundle\Controller\ApiController
    prefix:   api/

proposals:
    type:     rest
    resource: AppBundle\Controller\ProposalsController
    prefix:   api/

votes:
    type:     rest
    resource: AppBundle\Controller\VotesController
    prefix:   api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc