app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    path:     api/login_check
    methods:  POST
    defaults: { _controller: FOSUserBundle:Security:check }

proposals:
    type:     rest
    resource: AppBundle\Controller\ProposalsController
    prefix:   api/

votes:
    type:     rest
    resource: AppBundle\Controller\VotesController
    prefix:   api/